import type { Metadata } from "next";
import "./globals.css"; // Ensure globals.css is imported
import { outfit } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${outfit.className}`}>{children}</body>
    </html>
  );
}
